project:
  type: website
  output-dir: docs
  resources:
    - content/files

website:
  title: "ChIP-seq Modular Analysis Pipeline"
  sidebar:
    style: docked
    search: true
    contents:
      - content/index.qmd
      - content/overview.qmd
      - content/installation.qmd  
      - content/reference_setup.qmd
      - content/pipeline1.qmd
      - content/pipeline2.qmd
      - content/mapping.qmd
      - content/docker_pipeline1.qmd
      - content/docker_pipeline2.qmd
      - content/docker_guide.qmd
      - content/Conda.qmd
      - content/software.qmd
      - content/troubleshooting.qmd
      - content/citations.qmd
      - content/license.qmd

format:
  html:
    theme: cerulean
    toc: true
    toc-depth: 3
    number-sections: true
    code-fold: false
    css: styles.css

